export const constantText = {
  myPortFolio: " MY PORTFOLIO",
  home: "Home",
  resume: "Resume",
  projects: "Projects",
  title: "React and React-Native Developer",
  skills: "HTML/CSS | JavaScript | React | React Native | Firebase | GitHub",
  nameConstant: "Vishwanath S",
  skillConstant: "React and React-Native Developer",
  phone: "Phone",
  phoneNumber: "7760392920",
  email: "Email",
  emailId: "vishwanathsomavarad@gmail.com",
  linkedin: "Linkedin",
  linkedinUrl: "https://www.linkedin.com/in/vishwa-s-635b201a1",
  education: "Education",
  collageName: "BE in Computer Science and Engineering",
  place: "SKSVMACET LAXMESHWAR",
  jobDetails: "Job Details",
  comapanyName: "SOFTSUAVE TECHNOLOGY [Software Engineer ]",
  skills2: "Skills",
  url1: `https://i.pinimg.com/originals/d9/d2/82/d9d282bfd1842ef06e706a12679e7e49.jpg`,
  url1Desc: `The weather app provides weather conditions for the searched place and also provide local weather alerts.`,
  url2: `https://divyanet.com/wp-content/uploads/2020/03/latest-insta-icon.jpg`,
  url2Desc: `Image-gram proivides user to upload our favorite photos from your computer, tablet or mobile. 
  This one i built using react and firebase`,
};
